apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-nodejs-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/adirothbuilds/sample-nodejs-devops-task.git
    targetRevision: main
    path: chart/sample-nodejs
    helm:
      valueFiles:
        - ../../config/demo/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-nodejs-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
