name: CI Pipeline for Helm Chart
on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
  pull_request:
    paths:
      - 'chart/**'
jobs:
  lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: '3.12.0'
      - run: helm lint ./chart/sample-nodejs
  template:
    name: Dry-run Render Helm Chart
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: '3.12.0'
      - run: helm template ./chart/sample-nodejs